[package]
name = "llvm-not"
version = "0.1.0"
edition = "2018"

[target.'cfg(unix)'.dependencies]
libc = "0.2.98"

[dependencies]
find-program-by-name = { git = "https://github.com/broadwaylamb/find-program-by-name-rs", version = "0.1.0" }

[[bin]]
name = "not"
path = "src/main.rs"
